name: quiz_app
description: A Quiz App
publish_to: 'none' # Remove this line if you want to publish to pub.dev

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.0.11
  provider: ^6.1.2

flutter:
  uses-material-design: true

environment:
  sdk: '^3.6.0'
